# Public R workflow for longitudinal heat-wave and dust-storm symptom analysis.
# The input is synthetic data generated by scripts/01_generate_synthetic_data.R.

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(stringr)
  library(ggplot2)
  library(geepack)
  library(lme4)
  library(emmeans)
  library(readr)
})

data_path <- "data/synthetic_ncd_heatwave_panel.csv"
if (!file.exists(data_path)) {
  source("scripts/01_generate_synthetic_data.R")
}

dir.create("results", showWarnings = FALSE, recursive = TRUE)
dir.create("results/plots", showWarnings = FALSE, recursive = TRUE)

dat <- read_csv(data_path, show_col_types = FALSE) %>%
  mutate(
    phase = factor(phase, levels = c("T1", "T2", "T3")),
    ID = factor(ID),
    age_group = factor(age_group),
    gender = factor(gender),
    family_size_group = factor(family_size_group,
                               levels = c("1-2", "3-5", "6-8", "9+")),
    monthly_income_group = factor(monthly_income_group,
                                  levels = c("less than 100 JD",
                                             "100 - 200 JD",
                                             "200 JD or more")),
    household_area_group = factor(household_area_group)
  )

phase_prevalence <- dat %>%
  group_by(phase, heatwave_max_c, event_window) %>%
  summarise(
    observations = n(),
    heatwave_affected_rate = mean(heatwave_affected),
    duststorm_affected_rate = mean(duststorm_affected),
    dyspnea_rate = mean(dyspnea),
    fatigue_rate = mean(fatigue),
    allergy_rate = mean(allergy),
    mean_severity_score = mean(symptom_severity_score),
    .groups = "drop"
  )

write_csv(phase_prevalence, "results/phase_prevalence.csv")

fit_gee <- function(outcome, data = dat, corstr = "exchangeable") {
  rhs <- paste(
    "phase + age_group + gender + family_size_group + monthly_income_group",
    "+ household_area_group + HTN_prior + Asthma_prior + Thyroid_prior + CVDs_prior"
  )
  form <- as.formula(paste(outcome, "~", rhs))
  geeglm(
    form,
    id = ID,
    waves = phase_num,
    data = data,
    family = binomial(link = "logit"),
    corstr = corstr
  )
}

tidy_gee_or <- function(fit, outcome) {
  coefs <- as.data.frame(summary(fit)$coefficients)
  coefs$term <- rownames(coefs)
  names(coefs) <- make.names(names(coefs))
  p_col <- grep("^Pr", names(coefs), value = TRUE)[1]
  data.frame(
    outcome = outcome,
    term = coefs$term,
    estimate = coefs$Estimate,
    std_error = coefs$Std.err,
    odds_ratio = exp(coefs$Estimate),
    conf_low = exp(coefs$Estimate - 1.96 * coefs$Std.err),
    conf_high = exp(coefs$Estimate + 1.96 * coefs$Std.err),
    p_value = coefs[[p_col]],
    row.names = NULL
  )
}

outcomes <- c(
  "heatwave_affected", "duststorm_affected",
  "dyspnea", "fatigue", "allergy"
)

gee_results <- bind_rows(lapply(outcomes, function(y) {
  tidy_gee_or(fit_gee(y), y)
}))

write_csv(gee_results, "results/gee_odds_ratios.csv")

trend_plot <- dat %>%
  select(phase, heatwave_affected, duststorm_affected, dyspnea, fatigue, allergy) %>%
  pivot_longer(-phase, names_to = "outcome", values_to = "value") %>%
  group_by(phase, outcome) %>%
  summarise(rate = mean(value), .groups = "drop") %>%
  mutate(
    outcome = recode(
      outcome,
      heatwave_affected = "Heat-wave affected",
      duststorm_affected = "Dust-storm affected",
      dyspnea = "Dyspnea",
      fatigue = "Fatigue",
      allergy = "Allergy"
    )
  )

phase_plot <- ggplot(trend_plot, aes(x = phase, y = rate, group = outcome, color = outcome)) +
  geom_line(linewidth = 0.9) +
  geom_point(size = 2.2) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(
    title = "Synthetic phase trend for climate-sensitive NCD symptoms",
    x = "Survey phase",
    y = "Observed rate",
    color = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "bottom",
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA)
  )

ggsave("results/plots/synthetic_phase_symptom_trends.png", plot = phase_plot,
       width = 8.5, height = 5.2, dpi = 160, bg = "white")

dat <- dat %>%
  mutate(
    phase_num_centered = phase_num - mean(phase_num)
  )

fit_factor <- glmer(
  heatwave_affected ~ phase + age_group + gender + family_size_group +
    monthly_income_group + household_area_group + HTN_prior + Asthma_prior +
    Thyroid_prior + CVDs_prior + (1 | ID),
  family = binomial,
  data = dat,
  control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e5))
)

fit_linear <- glmer(
  heatwave_affected ~ phase_num + age_group + gender + family_size_group +
    monthly_income_group + household_area_group + HTN_prior + Asthma_prior +
    Thyroid_prior + CVDs_prior + (1 | ID),
  family = binomial,
  data = dat,
  control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e5))
)

fit_quadratic <- glmer(
  heatwave_affected ~ phase_num_centered + I(phase_num_centered^2) +
    age_group + gender + family_size_group + monthly_income_group +
    household_area_group + HTN_prior + Asthma_prior + Thyroid_prior +
    CVDs_prior + (1 | ID),
  family = binomial,
  data = dat,
  control = glmerControl(optimizer = "bobyqa", optCtrl = list(maxfun = 2e5))
)

aic_table <- data.frame(
  model = c("categorical_phase", "linear_phase", "quadratic_phase"),
  AIC = c(AIC(fit_factor), AIC(fit_linear), AIC(fit_quadratic))
) %>%
  arrange(AIC)

write_csv(aic_table, "results/glmm_time_spec_aic.csv")

phase_contrasts <- as.data.frame(
  summary(pairs(emmeans(fit_factor, ~ phase)), type = "response")
)
write_csv(phase_contrasts, "results/glmm_phase_contrasts.csv")

message("Analysis complete. Review the files in results/.")
